// <auto-generated />
namespace BLL.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AmendCommentModelAndAddPersonalDataNicknameUniqueConstraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AmendCommentModelAndAddPersonalDataNicknameUniqueConstraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202203161240143_AmendCommentModelAndAddPersonalDataNicknameUniqueConstraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
